import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

/**
 * MSW worker for the browser (dev), started from `main.tsx` only when `VITE_ENABLE_MSW=true`.
 * Requires `public/mockServiceWorker.js` (generated by `msw init public`).
 */
export const worker = setupWorker(...handlers)
