package no.rauboti.tome.rulesets

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.springframework.core.io.ClassPathResource
import tools.jackson.databind.JsonNode
import tools.jackson.module.kotlin.jacksonObjectMapper

/**
 * Guards the bundled OGL 3.5 SRD spell catalog (T112) — `rulesets/dnd35/spells.json`, sourced from
 * d20srd.org and generated by `tools/build-spells.mjs`. Loads the file and spot-checks a few known
 * per-class spell levels, so a bad rebuild or accidental edit surfaces immediately. Pure — no Spring/DB.
 */
class SpellCatalogTest {
    private val spells: JsonNode =
        ClassPathResource("rulesets/dnd35/spells.json").inputStream.use { jacksonObjectMapper().readTree(it) }["spells"]

    private fun spell(id: String): JsonNode = spells.first { it["id"].asText() == id }

    private fun level(
        id: String,
        cls: String,
    ): Int? = spell(id)["classLevels"][cls]?.asInt()

    @Test
    fun `catalog loads the full SRD spell set, every entry well-formed`() {
        assertTrue(spells.size() >= 500, "expected the full SRD (~591), got ${spells.size()}")
        spells.forEach {
            assertTrue(it["id"].asText().isNotBlank())
            assertTrue(it["name"].asText().isNotBlank())
            assertTrue(it["classLevels"].size() >= 1, "${it["id"].asText()} has no class levels")
        }
    }

    @Test
    fun `spot-checks known per-class spell levels`() {
        assertEquals(3, level("fireball", "sorcerer"))
        assertEquals(3, level("fireball", "wizard"))
        assertEquals(1, level("cureLightWounds", "cleric"))
        assertEquals(2, level("cureLightWounds", "ranger")) // rangers get it a level later
        assertEquals(9, level("wish", "wizard"))
        assertEquals(1, level("bless", "paladin"))
    }

    @Test
    fun `spell ids are unique`() {
        val ids = mutableListOf<String>()
        spells.forEach { ids.add(it["id"].asText()) }
        assertEquals(ids.size, ids.toSet().size, "duplicate spell ids in the catalog")
    }
}
