package no.rauboti.tome.rulesets

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.springframework.core.io.ClassPathResource
import tools.jackson.databind.JsonNode
import tools.jackson.module.kotlin.jacksonObjectMapper

/**
 * Guards the bundled OGL 3.5 SRD spell catalog (T112, schools T117) — `rulesets/dnd35/spells.json`,
 * sourced from d20srd.org and generated by `tools/build-spells.mjs`. Spot-checks known per-class spell
 * levels and schools so a bad rebuild or accidental edit surfaces immediately. Pure — no Spring/DB.
 */
class SpellCatalogTest {
    private val spells: JsonNode =
        ClassPathResource("rulesets/dnd35/spells.json").inputStream.use { jacksonObjectMapper().readTree(it) }["spells"]

    private fun spell(id: String): JsonNode = spells.first { it["id"].asText() == id }

    private fun level(
        id: String,
        cls: String,
    ): Int? = spell(id)["classLevels"][cls]?.asInt()

    /** Element texts of an array node. Built by iteration — `map` on a Jackson 3 `JsonNode` binds the node itself. */
    private fun texts(node: JsonNode?): List<String> {
        val out = mutableListOf<String>()
        node?.forEach { out.add(it.asText()) }
        return out
    }

    @Test
    fun `catalog loads the full SRD spell set, every entry well-formed`() {
        assertTrue(spells.size() >= 500, "expected the full SRD (~591), got ${spells.size()}")
        spells.forEach {
            assertTrue(it["id"].asText().isNotBlank())
            assertTrue(it["name"].asText().isNotBlank())
            assertTrue(it["classLevels"].size() >= 1, "${it["id"].asText()} has no class levels")
        }
    }

    @Test
    fun `spot-checks known per-class spell levels`() {
        assertEquals(3, level("fireball", "sorcerer"))
        assertEquals(3, level("fireball", "wizard"))
        assertEquals(1, level("cureLightWounds", "cleric"))
        assertEquals(2, level("cureLightWounds", "ranger")) // rangers get it a level later
        assertEquals(9, level("wish", "wizard"))
        assertEquals(1, level("bless", "paladin"))
    }

    @Test
    fun `spell ids are unique`() {
        val ids = mutableListOf<String>()
        spells.forEach { ids.add(it["id"].asText()) }
        assertEquals(ids.size, ids.toSet().size, "duplicate spell ids in the catalog")
    }

    @Test
    fun `every spell carries one of the nine 3_5 schools`() {
        spells.forEach {
            val school = it["school"]?.asText()
            assertTrue(
                school in SCHOOLS,
                "${it["id"].asText()} has school \"$school\", not one of the nine 3.5 schools",
            )
        }
    }

    @Test
    fun `spot-checks known schools, subschools and descriptors`() {
        assertEquals("Evocation", spell("fireball")["school"].asText())
        assertEquals("Universal", spell("wish")["school"].asText())

        // Subschool and descriptors are parsed out of the SRD's "School (Subschool) [Descriptor]" line.
        val cure = spell("cureLightWounds")
        assertEquals("Conjuration", cure["school"].asText())
        assertEquals("Healing", cure["subschool"].asText())

        val bless = spell("bless")
        assertEquals("Enchantment", bless["school"].asText())
        assertEquals("Compulsion", bless["subschool"].asText())
        assertEquals(listOf("Mind-Affecting"), texts(bless["descriptors"]))

        assertEquals(listOf("Fire"), texts(spell("fireball")["descriptors"]))
    }

    @Test
    fun `subschool and descriptors are omitted rather than empty when the SRD gives none`() {
        val entangle = spell("entangle") // "Transmutation" — no subschool, no descriptors
        assertEquals("Transmutation", entangle["school"].asText())
        assertTrue(entangle["subschool"] == null, "absent subschool should be omitted, not null/blank")
        assertTrue(entangle["descriptors"] == null, "absent descriptors should be omitted, not an empty array")
    }

    private companion object {
        val SCHOOLS =
            setOf(
                "Abjuration",
                "Conjuration",
                "Divination",
                "Enchantment",
                "Evocation",
                "Illusion",
                "Necromancy",
                "Transmutation",
                "Universal",
            )
    }
}
